### ISSUE TITLE
Prefix wildcard matching is required

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/govanityurls#18]
Currently, govanityurls looks for an exact prefix match for the paths provided in the configuration file.

```
host: my.org

paths:
   - /example/helloworld
        repo: ....
   - /
        repo: .... 
```

If user asks for `my.org/x`, govanityurls return a 404 instead of matching it with the second rule.

What's expected is that we should match `/x` with the `/` rule.
